/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Movie {
  'title' : string,
  'duration' : bigint,
  'recapScript' : string,
  'year' : bigint,
  'genre' : string,
  'posterUrl' : string,
  'backdropUrl' : string,
}
export interface _SERVICE {
  'addMovie' : ActorMethod<
    [string, string, bigint, bigint, string, string, string],
    undefined
  >,
  'addToList' : ActorMethod<[string], undefined>,
  'getList' : ActorMethod<[], Array<Movie>>,
  'getMovie' : ActorMethod<[string], Movie>,
  'removeFromList' : ActorMethod<[string], undefined>,
  'searchMovies' : ActorMethod<[string], Array<Movie>>,
  'seedData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];