/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Movie = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'recapScript' : IDL.Text,
  'year' : IDL.Nat,
  'genre' : IDL.Text,
  'posterUrl' : IDL.Text,
  'backdropUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMovie' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addToList' : IDL.Func([IDL.Text], [], []),
  'getAllMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
  'getList' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
  'getMovie' : IDL.Func([IDL.Text], [Movie], ['query']),
  'removeFromList' : IDL.Func([IDL.Text], [], []),
  'searchMovies' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Movie = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'recapScript' : IDL.Text,
    'year' : IDL.Nat,
    'genre' : IDL.Text,
    'posterUrl' : IDL.Text,
    'backdropUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'addMovie' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addToList' : IDL.Func([IDL.Text], [], []),
    'getAllMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
    'getList' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
    'getMovie' : IDL.Func([IDL.Text], [Movie], ['query']),
    'removeFromList' : IDL.Func([IDL.Text], [], []),
    'searchMovies' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };